name: Test
on: [ push ]
jobs:
  test:
    strategy:
      matrix:
        platform:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
        # TODO: Add support for Go tip. See https://github.com/actions/setup-go/issues/21
        go-version:
          - '1.17.x'
          - '1.18.x'
          - '1.19.x'
          - '1.20.x'
          - '1.21.x'
          - '1.22.x'
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test -v -race ./...
